spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
