spring:
  application:
    name: app

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
