spring:
  application:
    name: app

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://8c0ffcce91c21e9ad72b0c4b069d2967@o4508937992077312.ingest.de.sentry.io/4508938054074448
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true